name: mazzlabs-portfolio
services:
- name: web
  source_dir: /
  github:
    repo: Mazzlabs/Mazzlabs.works
    branch: main
  run_command: gunicorn --worker-tmp-dir /dev/shm --config gunicorn_config.py app:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: EMAIL_USERNAME
    scope: RUN_TIME
    type: SECRET
  - key: EMAIL_PASSWORD
    scope: RUN_TIME
    type: SECRET
  - key: CONTACT_EMAIL
    scope: RUN_TIME
    value: joseph@mazzlabs.works
  - key: FLASK_ENV
    scope: RUN_TIME
    value: production
